services:
  accounts_svc:
    image: swatkat1977/items:items_accounts_svc-${ACCOUNTS_SVC_DOCKER_TAG}
    container_name: accounts_svc
    ports:
      - "4000:4000"
    networks:
      - backend
    environment:
      - SERVICE_NAME=items_accounts_svc
      - ITEMS_ENVIRONMENT=development
    volumes:
      - "${ITEMS_DOCKER_ACCOUNTS_SVC_CONFIG_FILE}:/usr/local/items/accounts_svc.config"
      - "${ITEMS_DOCKER_ACCOUNTS_SVC_DB_FILE}:/usr/local/items/accounts_svc.db"
    env_file:
      - .env

  cms_svc:
    image: swatkat1977/items:items_cms_svc-${CMS_SVC_DOCKER_TAG}
    container_name: cms_svc
    ports:
      - "5050:5050"
    networks:
      - backend
    environment:
      - SERVICE_NAME=cms_accounts_svc
      - ITEMS_ENVIRONMENT=development
    volumes:
      - "${ITEMS_DOCKER_CMS_SVC_CONFIG_FILE}:/usr/local/items/cms_svc.config"
      - "${ITEMS_DOCKER_CMS_SVC_DB_FILE}:/usr/local/items/cms_svc.db"
    env_file:
      - .env

  gateway_svc:
    image: swatkat1977/items:items_gateway_svc-${GATEWAY_SVC_DOCKER_TAG}
    container_name: gateway_svc
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - SERVICE_NAME=gateway_svc
      - ITEMS_ENVIRONMENT=development
    volumes:
      - "${ITEMS_DOCKER_GATEWAY_SVC_CONFIG_FILE}:/usr/local/items/gateway_svc.config"
      - "${ITEMS_DOCKER_GATEWAY_SVC_METADATA_CONFIG_FILE}:/usr/local/items/metadata.config"
    env_file:
      - .env

  web_portal_svc:
    image: swatkat1977/items:items_web_portal_svc-${WEB_PORTAL_SVC_DOCKER_TAG}
    container_name: web_portal_svc
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - SERVICE_NAME=web_portal_svc
      - ITEMS_ENVIRONMENT=development
    volumes:
      - "${ITEMS_DOCKER_WEB_PORTAL_SVC_CONFIG_FILE}:/usr/local/items/web_portal_svc.config"
    env_file:
      - .env

networks:
  backend:
    driver: bridge