import unittest
from test_apis_web_session_api_view import TestHandshakeApiView
from test_application import TestApplication
from test_threadsafe_configuration import TestThreadSafeConfiguration
from test_sessions import TestSessions
from test_apis_web_projects_api_view import TestApiProjectApiView
from test_api_web_testcases_api_view import TestApiTestcaseApiView
from test_metadata_handler import TestMetadataHandler
from test_apis_web_webhook_api_view import TestWebhookApiProjectApiView

if __name__ == "__main__":
    unittest.main()
