FROM python:3.14.6-alpine

# Add a user and group for ITEMS and then setup file paths.
RUN addgroup -S items && \
    adduser -S items -G items && \
    mkdir /usr/local/items &&  \
    mkdir /usr/local/items/services &&  \
    chown items:items /usr/local/items

WORKDIR /usr/local/items

# Install Python dependencies
COPY requirements/requirements_web_portal.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements_web_portal.txt

# Copy application
COPY --chown=items:items items ./items

# Runtime configuration
ENV PYTHONPATH=/usr/local/items

# These should match the names your application actually uses
ENV ITEMS_WEB_PORTAL_CONFIG_FILE_REQUIRED=1
ENV ITEMS_WEB_PORTAL_CONFIG_FILE=/usr/local/items/web_portal.cfg

# Listen on all interfaces inside the container
ENV ITEMS_WEB_PORTAL_HOST=0.0.0.0
ENV ITEMS_WEB_PORTAL_PORT=8000

# Optional logging
ENV LOGGING_LOG_LEVEL=DEBUG

EXPOSE 8000

USER items

CMD ["python", "-m", "items.services.items_web_portal.run"]
