name: Unit Tests & Coverage | Account Svc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Adjust to your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install jsonschema
          pip install aiohttp
          pip install quart

      # Step 4: Run tests and measure coverage
      - name: Run tests with coverage
        env:
          PYTHONPATH: items/shared:items/unittests_accounts_svc:items/accounts_svc
        run: |
          coverage run --rcfile=./items/.coveragerc_accounts_svc -m unittest -v main
          coverage report -m --fail-under=100
