name: Perform Lint

on:
  pull_request:
    paths:
      - 'items/accounts_svc/**'
      - 'items/gateway_svc/**'
      - 'items/shared/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['accounts_svc', 'gateway_svc', 'shared']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in directory
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            items:
              - 'items/${{ matrix.directory }}/**'

      - name: Run lint for ${{ matrix.directory }}
        if: steps.changes.outputs.items == 'true'
        run: echo "Running lint for items/${{ matrix.directory }}"
        # Add your actual linting steps here