name: Perform Lint

on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      accounts_svc_changed: ${{ steps.detect.outputs.accounts_svc_changed }}
      gateway_svc_changed: ${{ steps.detect.outputs.gateway_svc_changed }}
      shared_changed: ${{ steps.detect.outputs.shared_changed }}
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Detect changes in directories
        id: detect
        run: |
          echo "Checking for changes in items/accounts_svc/"
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q '^items/accounts_svc/'; then
            echo "accounts_svc_changed=true" >> $GITHUB_OUTPUT
          else
            echo "accounts_svc_changed=false" >> $GITHUB_OUTPUT
          fi

          echo "Checking for changes in items/gateway_svc/"
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q '^items/gateway_svc/'; then
            echo "gateway_svc_changed=true" >> $GITHUB_OUTPUT
          else
            echo "gateway_svc_changed=false" >> $GITHUB_OUTPUT
          fi

          echo "Checking for changes in items/shared/"
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q '^items/shared/'; then
            echo "shared_changed=true" >> $GITHUB_OUTPUT
          else
            echo "shared_changed=false" >> $GITHUB_OUTPUT
          fi

  accounts-svc-lint:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.accounts_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lint for accounts_svc
        run: echo "Running lint for items/accounts_svc"
        # Add your actual linting steps here

  gateway-svc-lint:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.gateway_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lint for gateway_svc
        run: echo "Running lint for items/gateway_svc"
        # Add your actual linting steps here

  shared-lint:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.shared_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lint for shared
        run: echo "Running lint for items/shared"
        # Add your actual linting steps here