name: Perform Lint

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code with full history
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust to your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage jsonschema aiohttp quart pylint

  detect-changes:
    runs-on: ubuntu-latest
    needs: setup  # Wait for the setup job to complete
    outputs:
      accounts_svc_changed: ${{ steps.detect.outputs.accounts_svc_changed }}
      gateway_svc_changed: ${{ steps.detect.outputs.gateway_svc_changed }}
      shared_changed: ${{ steps.detect.outputs.shared_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the head commit of the PR

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}  # Fetch the base branch

      - name: Detect changes in directories
        id: detect
        run: |
          echo "Checking for changes in items/accounts_svc/"
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }} | grep -q '^items/accounts_svc/'; then
            echo "accounts_svc_changed=true" >> $GITHUB_OUTPUT
          else
            echo "accounts_svc_changed=false" >> $GITHUB_OUTPUT
          fi

          echo "Checking for changes in items/gateway_svc/"
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }} | grep -q '^items/gateway_svc/'; then
            echo "gateway_svc_changed=true" >> $GITHUB_OUTPUT
          else
            echo "gateway_svc_changed=false" >> $GITHUB_OUTPUT
          fi

          echo "Checking for changes in items/shared/"
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }} | grep -q '^items/shared/'; then
            echo "shared_changed=true" >> $GITHUB_OUTPUT
          else
            echo "shared_changed=false" >> $GITHUB_OUTPUT
          fi

  accounts-svc-lint:
    runs-on: ubuntu-latest
    needs: [setup, detect-changes]  # Wait for both setup and detect-changes
    if: needs.detect-changes.outputs.accounts_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Pylint
        env:
          PYTHONPATH: items/shared:items/accounts_svc
        run: |
          pylint --fail-under=10.0 items/accounts_svc

  gateway-svc-lint:
    runs-on: ubuntu-latest
    needs: [setup, detect-changes]  # Wait for both setup and detect-changes
    if: needs.detect-changes.outputs.gateway_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Pylint
        env:
          PYTHONPATH: items/shared:items/gateway_svc
        run: |
          pylint --fail-under=10.0 items/gateway_svc

  shared-lint:
    runs-on: ubuntu-latest
    needs: [setup, detect-changes]  # Wait for both setup and detect-changes
    if: needs.detect-changes.outputs.shared_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Pylint
        env:
          PYTHONPATH: items/shared
        run: |
          pylint --fail-under=10.0 items/shared