name: Code Coverage | Shared

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Adjust to your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      # Step 4: Run tests and measure coverage
      - name: Run tests with coverage
        env:
          PYTHONPATH: items/shared:items/unittests_shared
        run: |
          coverage run -m unittest -v unittests_shared/main.py
          coverage report -m --fail-under=80

      # Step 5: Upload coverage results as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: shared-coverage-report
          path: .coverage