name: Linting | Shared

on:
  pull_request:
    paths:
      - 'items/shared/**'
      - 'items/unittests_shared/**'
      - '.github/workflows/shared_lint.yml'

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install jsonschema
          pip install aiohttp

      - name: Run Pylint
        env:
          PYTHONPATH: items/shared
        run: |
          pylint --fail-under=10.0 items/shared