name: Validate Branch (lint & unittests)

on:
  pull_request:

permissions:
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    outputs:
      identity_svc_changed: ${{ steps.detect.outputs.identity_svc_changed }}
      cms_svc_changed: ${{ steps.detect.outputs.cms_svc_changed }}
      gateway_svc_changed: ${{ steps.detect.outputs.gateway_svc_changed }}
      web_portal_svc_changed: ${{ steps.detect.outputs.web_portal_svc_changed }}
      shared_changed: ${{ steps.detect.outputs.shared_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the head commit of the PR

      - name: Detect changes in directories
        id: detect
        run: |
          git fetch origin "${{ github.event.pull_request.base.ref }}" --depth=1
          changed_files=$(git diff --name-only "origin/${{ github.event.pull_request.base.ref }}" "${{ github.event.pull_request.head.sha }}")

          echo "Checking for changes in items/services/items_identity"
          if echo "$changed_files" | grep -qE '^(items/services|unit_tests)/items_identity/'; then
            echo "identity_svc_changed=true" >> $GITHUB_OUTPUT
            echo "[INFO] Identity Service or it's unit tests have changed"
          else
            echo "identity_svc_changed=false" >> $GITHUB_OUTPUT
            echo "[INFO] Identity Service or it's unit tests have NOT changed"
          fi

          echo "Checking for changes in items/services/items_cms/"
          if echo "$changed_files" | grep -qE '^(items/services|unit_tests)/items_cms/'; then
            echo "cms_svc_changed=true" >> $GITHUB_OUTPUT
            echo "[INFO] CMS Service or it's unit tests have changed"
          else
            echo "cms_svc_changed=false" >> $GITHUB_OUTPUT
            echo "[INFO] CMS Service or it's unit tests have NOT changed"
          fi

          echo "Checking for changes in items/services/items_gateway/"
          if echo "$changed_files" | grep -qE '^(items/services|unit_tests)/items_gateway/'; then
            echo "gateway_svc_changed=true" >> $GITHUB_OUTPUT
            echo "[INFO] Gateway Service or unit tests have changed"
          else
            echo "gateway_svc_changed=false" >> $GITHUB_OUTPUT
            echo "[INFO] Gateway Service or unit tests have NOT changed"
          fi

          echo "Checking for changes in items/services/items_web_portal/"
          if echo "$changed_files" | grep -qE '^(items/services|unit_tests)/web_portal_svc/'; then
            echo "web_portal_svc_changed=true" >> $GITHUB_OUTPUT
            echo "[INFO] services/web_portal_svc has changed"
          else
            echo "web_portal_svc_changed=false" >> $GITHUB_OUTPUT
            echo "[INFO] Web Portal Service or unit tests have NOT changed"
          fi

          echo "Checking for changes in items/shared/"
          if echo "$changed_files" | grep -qE '^(items|unit_tests)/shared/'; then
            echo "shared_changed=true" >> $GITHUB_OUTPUT
            echo "[INFO] items/shared has changed"
          else
            echo "shared_changed=false" >> $GITHUB_OUTPUT
          fi

  verify_identity-svc:
    runs-on: ubuntu-24.04
    needs: detect-changes  # Wait for detect-changes
    if: needs.detect-changes.outputs.identity_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements_identity.txt
          pip install coverage pylint

      - name: Run Pylint
        env:
          PYTHONPATH: .
        run: |
          pylint --fail-under=10.0 items/services/items_identity

      # Run tests and measure coverage
      - name: Run tests with coverage
        env:
          PYTHONPATH: .:items/services/items_identity:unit_tests/items_identity
        run: |
          coverage run --rcfile=.github/workflows/.coveragerc_identity_svc -m unittest -v unit_tests/items_identity/main.py
          coverage report -m --fail-under=100

  verify_cms-svc:
    runs-on: ubuntu-24.04
    needs: detect-changes  # Wait for detect-changes
    if: needs.detect-changes.outputs.cms_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements_cms.txt
          pip install coverage pylint

      - name: Run Pylint
        env:
          PYTHONPATH: .
        run: |
          pylint --fail-under=10.0 items/services/items_cms

      # Run tests and measure coverage
      - name: Run tests with coverage
        env:
          PYTHONPATH: unit_tests/items_cms
        run: |
          coverage run --rcfile=.github/workflows/.coveragerc_cms_svc -m unittest -v unit_tests/items_cms/main.py
          coverage report -m --fail-under=100

  verify_gateway-svc:
    runs-on: ubuntu-24.04
    needs: detect-changes  # Wait for detect-changes
    if: needs.detect-changes.outputs.gateway_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage jsonschema aiohttp quart pylint tzlocal

      - name: Run Pylint
        env:
          PYTHONPATH: .
        run: |
          pylint --fail-under=10.0 items/services/items_gateway

      # Run tests and measure coverage
      - name: Run tests with coverage
        env:
          PYTHONPATH: .
        run: |
          coverage run --rcfile=.github/workflows/.coveragerc_gateway_svc -m unittest -v main
          coverage report -m --fail-under=100

  verify_web-portal-svc:
    runs-on: ubuntu-24.04
    needs: detect-changes  # Wait for detect-changes
    if: needs.detect-changes.outputs.web_portal_svc_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage jsonschema aiohttp quart pylint

      - name: Run Pylint
        env:
          PYTHONPATH: .
        run: |
          pylint --fail-under=10.0 items/services/web_portal_svc

      # Run tests and measure coverage
      - name: Run tests with coverage
        env:
          PYTHONPATH: items/shared:unit_tests/web_portal_svc:services/web_portal_svc:common
        run: |
          coverage run --rcfile=.github/workflows/.coveragerc_web_portal_svc -m unittest -v main
          coverage report -m --fail-under=100

  shared-lint:
    runs-on: ubuntu-24.04
    needs: detect-changes  # Wait for detect-changes
    if: needs.detect-changes.outputs.shared_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage jsonschema aiohttp quart pylint

      - name: Run Pylint
        env:
          PYTHONPATH: items/shared
        run: |
          pylint --fail-under=10.0 items/shared

      # Run tests and measure coverage
      - name: Run tests with coverage
        env:
          PYTHONPATH: items/shared:unit_tests/shared
        run: |
          coverage run --rcfile=.github/workflows/.coveragerc_shared -m unittest -v main
          coverage report -m --fail-under=100
